---
- name: Bootstrap-OS | Fetch /etc/os-release
  raw: cat /etc/os-release
  register: os_release
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false
  environment: {}

- name: Bootstrap-OS | Set bootstrap_os
  set_fact:
    os_family: >-
      {%- if "Debian" in os_release.stdout or "Ubuntu" in os_release.stdout -%}
      debian
      {%- elif 'ALT' in os_release.stdout -%}
      altlinux
      {%- elif "CentOS" in os_release.stdout or "Red Hat Enterprise Linux" in os_release.stdout or "Oracle" in os_release.stdout -%}
      rhel
      {%- endif -%}

- name: Bootstrap-OS | Loading platform variables
  include_vars: "{{ os_family | lower }}.yml"

- name: Bootstrap-OS | Include task for Debian like systems
  include_tasks: bootstrap-debian.yml
  when: os_family == "debian"

- name: Bootstrap-OS | Include task fo AltLinux systems
  include_tasks: bootstrap-altlinux.yml
  when: os_family == "altlinux"

- name: Bootstrap-OS | Include task fo RHEL like systems
  include_tasks: bootstrap-rhel.yml
  when: os_family == "rhel"

- name: Bootstrap-OS | Remove require tty
  lineinfile:
    regexp: '^\w+\s+requiretty'
    dest: /etc/sudoers
    state: absent

- name: Bootstrap-OS | Create remote_tmp for it is used by another module
  file:
    path: "{{ ansible_remote_tmp | default('~/.ansible/tmp') }}"
    state: directory
    mode: "0700"
